language: go

go:
  - tip

install:
  - go get github.com/dchest/uniuri
  - go get github.com/ewhal/pygments
  - go get github.com/go-sql-driver/mysql
  - go get github.com/gorilla/mux
script:
- make
